language: java
jdk: oraclejdk11

branches:
  only:
    - develop
    - master

script:
  - mvn clean install

deploy:
  provider: cloudfoundry
  username: polushan@yandex.ru
  password: $cf-password
  api: https://api.run.pivotal.io
  organization: PingPong
  space: development
  manifest: manifest.yml
  app_name: ping-service