language: java
jdk: oraclejdk11

branches:
  only:
  - develop
  - master

before_install:
- chmod +x mvnw

deploy:
  provider: cloudfoundry
  username: polushan@yandex.ru
  api: https://api.run.pivotal.io
  organization: PingPong
  space: development
  manifest: manifest.yml
  app_name: ping-service
  on:
    branch: master
  password:
    secure: sqIcyxioW0IsNZsjRXLn0wa0TS+PTVF6WiDLvU79KE8o4Ie6W9k9V5fewHyb99YATJ9qjoL79YcUlGcjtKVAhVnWMau1Vww2FCA3rHa0iuWtrMBqrgCNrYDdwTPtw9pO2L5S4o87zRUetmm73stcIgriMgDbe0BWiRgzMhq9bPToV/0icgsoDMSZfRUudszt+cDmEEE2d6DyNwlZvwzxAkZQGSmYnFdMXsUKoUBsrkC1jrlWeSF66RZnqIDPEMiYgrQ4SqDDjea+QNqaTvx7yR20krRdKMbv3Zj8AdhCPE6/U7KxZQ04C8Ec/4LeScVLXvHlPoV806Nu/dLs0u7Ou3+tT8hcJhPQQl4Gxwvl0L7NQyFaNQw6/1onJkD1NkJnuSYu67KZjjcnGo1KyyEJFkAK5w3Ewe4hube0xVSbL5f3oSCrSmxsD6IEBvshdXwG//O6u5XfhW7TEjTRBblnpTl6MGETCMkFMk+z5fMG7cl2tRSSrpkCOIXxZN7FQ6Wd/KOhVT8QcaeSxKZDDmmVmqR1bRv6MsYlaX9uhsr2SdS8iKbF6u1/6QCKhLFnd87AtWlerT7Cevu1MwLT3IbvhWVJg5oYwxkbl1Vm8yYm0zgTKxtxnF74uDutbqV5XCnLNf0EPYRAp1sImN05FVpLKOoPsbuGRLLs/PhrMix4x3c=
