eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://discovery-cheerful-fox.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePortEnabled: false
    securePortEnabled: true

feign:
  hystrix:
    enabled: true