eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://pingpong-discovery.herokuapp.com/eureka
  instance:
    hostname: cloud-ping-service.herokuapp.com

feign:
  hystrix:
    enabled: true