eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://discovery-cheerful-fox.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}

feign:
  hystrix:
    enabled: true

pong:
  host: https://pong-service-happy-kob.cfapps.io